name: Android CI

on:
  push:
    branches: master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Dencrypt tar.gpg
      run: |
        mkdir $HOME/private
        gpg --quiet --batch --yes --decrypt --passphrase="${{ secret.FIREBASE_SECRET }}" \
                --output $HOME/private/services.tar services.tar.gpg
        tar xvf $HOME/private/services.tar
    - name: Build with Gradle
      run: ./gradlew build
